export const AUTOMATIC_DISCOUNTS = [
    {
        id:"1",
        label: "Discount name",
        discountType: "euro",
        discountData: 25000,
        duration: "",
        oneTime: true,
        isActive: true,
        description: "",
    },
    {
        id:"2",
        label: "Discount name",
        discountType: "percentage",
        discountData: 25,
        duration: "",
        oneTime: false,
        isActive: false,
        description: "",
    },
    {
        id:"3",
        label: "Discount name",
        discountType: "euro",
        discountData: 25000,
        duration: 1,
        oneTime: false,
        isActive: false,
        description: "",
    },
    {
        id:"4",
        label: "Discount name",
        discountType: "percentage",
        discountData: 25,
        duration: 3,
        oneTime: false,
        isActive: false,
        description: "",
    },
    {
        id:"5",
        label: "Discount name",
        discountType: "euro",
        discountData: 25000,
        duration: "",
        oneTime: true,
        isActive: false,
        description: "",
    },
    {
        id:"6",
        label: "Discount name",
        discountType: "euro",
        discountData: 25000,
        duration: 3,
        oneTime: false,
        isActive: false,
        description: "",
    },
    {
        id:"7",
        label: "Discount name",
        discountType: "euro",
        discountData: 25,
        duration: "",
        oneTime: true,
        isActive: false,
        description: "",
    },
]